### ISSUE TITLE
www.mpcatalog.net should redirect here or to some other content

### ISSUE THREAD

**Issue by clarkd** [MPCatalog/scom-community-catalog-ui#7]
Currently if you navigate to the above domain, it shows a generic Rebrandly parked page.

Ideally, it would redirect here or to some other explanatory content.

**Comment by P2P-Nathan** [comment]
Thank you for submitting the issue.  I will look at possible solutions and try to get a solution created by the 1.0.2.x bugfix release.

**Comment by P2P-Nathan** [comment]
this issue should now be resolved.  www.mpcatalog.net directs to a page with usable content now.
